package com.shestakam.tapestry.helloApp.entities.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.shestakam.tapestry.helloApp.entities.Address;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String PASSWORD_PROPERTY = "password";
    @Deprecated
    public static final String ADDRESS_PROPERTY = "address";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<String> PASSWORD = new Property<String>("password");
    public static final Property<List<Address>> ADDRESS = new Property<List<Address>>("address");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }

    public void addToAddress(Address obj) {
        addToManyTarget("address", obj, true);
    }
    public void removeFromAddress(Address obj) {
        removeToManyTarget("address", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Address> getAddress() {
        return (List<Address>)readProperty("address");
    }


}
